### ISSUE TITLE
Support openSUSE

### ISSUE THREAD

**Issue by boblmartens** [xenserver/xenadmin#1066]
In XenCenter for XenServer 7.0, openSUSE is not as well supported as many other distros. With the recent push of openSUSE Leap (being related to SLE 12), would it be possible to add support for openSUSE like we have support for Ubuntu?

I'm mainly thinking of having support in the install.sh script for the guest utilities and also showing up as an OS within XenCenter when viewing information about a VM.

Thanks!

**Comment by stephen-turner** [comment]
This is not a XenCenter issue, but a XenServer issue. I suggest filing a ticket at bugs.xenserver.org.
