### ISSUE TITLE
Put libxenserver on Github

### ISSUE THREAD

**Issue by kallisti5** [xenserver/xenadmin#1157]
There is an SDK for XenServer which contains a 'libxenserver' which looks like a nice interface to XenServer.  A real C / C++ / etc gui could be developed with this as a base... however it doesn't seem to exist anywhere easily accessible.

Lets put libxenserver on github so people can use it?  Hidden in some "SDK zip file" really doesn't help anyone put it to good use :-)

**Comment by kallisti5** [comment]
```
$ ./test_enumerate 192.168.1.20 root XXXX
------------------------------------------------------------------------------
Virtual Machine: Control domain on host: xensrv01
------------------------------------------------------------------------------
  uuid:                       e71XXXXX-e7a9-4129-9f3c-XXXXXcc34354
  power_state:                Running
  name_label:                 Control domain on host: xensrv01
  name_description:           The domain which manages physical devices and manages other domains
  user_version:               1
  is_a_template:              0
  memory_static_max:          788529152
  memory_static_min:          788529152
  memory_dynamic_max:         788529152
  memory_dynamic_min:         788529152
  vcpus_params:               
  vcpus_max:                  2
  vcpus_at_startup:           2
  actions_after_shutdown:     0
  actions_after_reboot:       0
  actions_after_crash:        0
  consoles:                   
    uuid:                     bc384ae1-38e8-5a70-2941-354f39192c4b
    protocol:                 vt100
    location:                 https://192.168.1.20/console?ref=OpaqueRef:a8d31bfb-a794-c9ae-2e29-26de02003f66
    other_config:             
    uuid:                     6e964205-3ef0-431a-ddc6-e1a387f1d7ef
    protocol:                 rfb
    location:                 https://192.168.1.20/console?ref=OpaqueRef:3a026ff8-a8ba-07c2-1710-f321403d7a22
    other_config:             
  VBDS:                       
  pv_bootloader:              
  pv_kernel:                  
  pv_ramdisk:                 
  pv_args:                    
  pv_bootloader_args:         
  hvm_boot_policy:            
  hvm_boot_params:            
  pci_bus:                    
  other_config:               
    [storage_driver_domain, OpaqueRef:7fde804c-c24d-c0e9-e562-73597b2f73db]
    [is_system_domain, true]  
    [perfmon, <config><variable><name value="fs_usage"/></variable><variable><name value="mem_usage"/></variable><variable><name value="log_fs_usage"/></variable></config>]
  domid:                      0
  is_control_domain:          1
------------------------------------------------------------------------------
```


Wow, this is a nice library... whomever wrote it knew what they were doing.  Instead of wasting time with dot.net which will never be really cross-platform, why not begin an experimental C / C++ based cross platform UI?  VMWare is scrambling to catch up and move their crappy flash web ui back to native... XenServer would of been a serious player if they had a portable native client.

**Comment by kallisti5** [comment]
Looks like a former Citrix Engineer in Japan already wrote a C++ GUI to manage XenServer instances.   http://www.hideakin.com/    "anago"   The code isn't in a version control system (git) though and it looks like you have to download the source file by file.

http://www.hideakin.com/anago_prp.png
http://www.hideakin.com/anago_hpf.png

The license isn't defined though and he has no contact methods listed.  (besides linked-in)
https://www.linkedin.com/in/hideaki-narita-6a737868

**Comment by stephen-turner** [comment]
The SDKs are already on github. At least, they are mostly autogenerated, but the autogeneration code, and the parts that aren't autogenerated, are all publicly available at https://github.com/xapi-project/xen-api-sdk.

Anyone is welcome to use them to create a new UI, indeed many people have already done so (XenOrchestra, for example).
