### ISSUE TITLE
When Selecting Boot Order, Don't De-select Option Unless Checkbox is Pressed

### ISSUE THREAD

**Issue by dzampino** [xenserver/xenadmin#1230]
Currently, you can't change the boot order with disabling a boot option. More of an annoyance than anything else.

**Comment by stephen-turner** [comment]
Thanks, @dzampino, I've raised a bug.

**Comment by stephen-turner** [comment]
Internal reference: CA-226256

**Comment by stephen-turner** [comment]
Fixed by #1237.
