### ISSUE TITLE
Cyclic dependency

### ISSUE THREAD

**Issue by johnbester** [xenserver/xenadmin#1289]
I am trying to compile XenAdmin for Linux using Mono. One thing that Mono does not allow is cyclic dependencies. This currently seems to be the only cyclic dependency that prevents a build:
XenOvfTransport/Export.cs depends on XenModel/XenRef.cs as well as XenModel/Session.cs
XenModel/ExportVmAction.cs depends on XenOvfTransport/Export.cs

By commenting out all references to code which directly or indirectly references Export class in ExportVmAction.cs, the build can complete without other cyclic dependencies.

**Comment by kc284** [comment]
XenModel does not depend on XenOvfTransport. That ExportVmAction exports to XVA format, not to OVF/OVA and uses the XenServer API, not the OvfApi. XenOvfTransport does indeed depend on XenModel, but it is referenced only by XenAdmin (XenAdmin/Actions/OVFActions). Could you share your build log? The problem might be elsewhere.

**Comment by kc284** [comment]
Closing this issue as invalid.
