### ISSUE TITLE
Compiling Resx error with non english VS

### ISSUE THREAD

**Issue by cocoon** [xenserver/xenadmin#1852]
Just a short note if anybody should have the same problem, so this could be closed directly.

If one is using a Visual Studio (I was using VS 2017, 15.4.3) in another language than english it fails to compile some ResX because the shortcuts like "ctrl+n" (XenAdmin\MainWindow.resx Line: 2309) are expected to be translated to that language.

One workaround: to compile it using english language pack

Microsoft: https://connect.microsoft.com/VisualStudio/feedback/details/361798/switching-visual-studio-2008-ide-language-from-english-to-german-produces-compiler-errors-on-resx-file

**Comment by borzel** [comment]
or replace "Ctrl+N" with "Control+N"  -> https://github.com/borzel/xenadmin/commit/555191eb723c9cbcd2ce0714f339c97330c2af4d

**Comment by borzel** [comment]
This issue can be closed -> https://github.com/xenserver/xenadmin/pull/2078 is merged
