### ISSUE TITLE
[Question] Interested in moving from NUnit2 to NUnit3 ?

### ISSUE THREAD

**Issue by borzel** [xenserver/xenadmin#2079]
We at XCP-ng Center (https://github.com/xcp-ng/xenadmin) are finally about to switch from NUnit2 to Nunit3. Are you interessted in this work? If yes, we'll be happy to provide you a PR.

You can have a look at: https://github.com/xcp-ng/xenadmin/commits/feature-nunit2-to-nunit3

**Comment by borzel** [comment]
anyone at home?

**Comment by borzel** [comment]
still no answer or reaction. Nobody there who can reply?

**Comment by kc284** [comment]
We're currently in the process of a larger overhaul of the unit tests, which includes, among other things, moving to nunit3.

**Comment by borzel** [comment]
Ok, so I close this. Feel free to use our results for toubleshooting purposes ;-)
