### ISSUE TITLE
Can't connect to XCP-ng Server V. 8.2

### ISSUE THREAD

**Issue by blu-IT** [xenserver/xenadmin#2751]
Hello,

I did an upgrade from XCP-ng server 7.6.1 -> 8.2.0 - everything went fine. But when I try to connect via XCP Center, it says:

"This version of XCP-g Center is outdated..."

![xcp](https://user-images.githubusercontent.com/13665806/100886880-9f854100-34b4-11eb-987f-40e8eb029b62.png)

What also makes me wonder: The server is running XCP-ng 8.2, not V. 7.6.1. Server was restarted after upgrade aund shows V. 8.2. Why does XCP-ng center still recognize V. 7.6.1? I also removed this server from XCP-ng Center and added him again - still the same message.

Thanks!

Regards

**Comment by kc284** [comment]
The message used in the above box is `This version of [XenCenter] is out of date and cannot connect to {0}...`, where the placeholder `{0}` is filled with the pool master's name. Is your server called "XCP-ng 7.6.1"?

**Comment by blu-IT** [comment]
@kc284 

Yes, that is possible. Thanks for the hint!

And do you also have an idea how to solve my main problem? Is XCP-ng Center not ready for the recent server edition?

**Comment by kc284** [comment]
This is a question for the XCP-ng project/fork, please have a look here https://github.com/xcp-ng/xenadmin.

**Comment by blu-IT** [comment]
Oh..., sure. Thanks!
