### ISSUE TITLE
Performance Counter IntelliCache Cache hits + misses not handled

### ISSUE THREAD

**Issue by cocoon** [xenserver/xenadmin#3080]
I don't know if it can happen in a real environment, but I think if IntelliCache is available and one selects a server and it's performance tab it throws exceptions here:

https://github.com/xenserver/xenadmin/blob/master/XenAdmin/Controls/CustomDataGraph/DataSet.cs#L87

Because the following two cases are not handled:

```
case "hits/s":
case "misses/s":
```

It just happened when I tested it against a VM and thought I would let you know.

![IntelliCache_Cache_Hits](https://user-images.githubusercontent.com/1071741/212325478-781b84a2-0ab1-4bb1-873c-ac5f86d25ffb.png)

**Comment by kc284** [comment]
It could be a regression related the logic changes in https://github.com/xenserver/xenadmin/pull/2848, Thanks for reporting it, I'll have a look at it and fix accordingly.
