### ISSUE TITLE
Typo in filename: VtmpManagementDialog.cs => VtpmManagementDialog.cs

### ISSUE THREAD

**Issue by stormi** [xenserver/xenadmin#3129]
Minor comment on this file: https://github.com/xenserver/xenadmin/blame/master/XenAdmin/Dialogs/VtmpManagementDialog.cs

It was prefixed with `Vtmp` instead of `Vtpm`.

**Comment by kc284** [comment]
Thanks, I'll correct it.

**Comment by kc284** [comment]
Fix in https://github.com/xenserver/xenadmin/pull/3139.
